### ISSUE TITLE
/lib/ folder is outdated and does not match current release

### ISSUE THREAD

**Issue by tieniber** [ivosturm/GoogleMapsCustomMarker#13]
It seems like your lib folder contains old dependencies instead of the jsapi.js file referenced in the widget.

**Comment by ivosturm** [comment]
Hi Eric,

Are you getting an error or..? Why do you  note this?

Let me know, thanks!

Op 20 jun. 2018 om 17:55 heeft tieniber <notifications@github.com<mailto:notifications@github.com>> het volgende geschreven:


It seems like your lib folder contains old dependencies instead of the jsapi.js file referenced in the widget.

**Comment by tieniber** [comment]
No error in your release, but if I fork your code and try to build the widget myself, it fails. The main widget code references jsapi.js but it's not in your repository. In the release mpk file, there is a jsapi.js file in the /lib/ folder. Just wanted to let you know so you could fix the repository.

**Comment by ivosturm** [comment]
Should be fixed with version 3.2.0 of widget
