### ISSUE TITLE
DEPRECATED: store.caller argument of mx.data.action will be removed in version 8.0. The originating page should be passed to mx.data.action as 'origin' instead.

### ISSUE THREAD

**Issue by ssuijkerbuijk** [ivosturm/GoogleMapsCustomMarker#14]
Warning "DEPRECATED: store.caller argument of mx.data.action will be removed in version 8.0. The originating page should be passed to mx.data.action as 'origin' instead. " when clicking the button which triggers the  "on click microflow".  (Button in the infowindow)

**Comment by ivosturm** [comment]
Hi,

Will update this when Mendix 8 is live, no need to fix this now, since it is only deprecated.

Kind regards,
Ivo

Van: ssuijkerbuijk <notifications@github.com>
Verzonden: woensdag 24 oktober 2018 07:56
Aan: ivosturm/GoogleMapsCustomMarker <GoogleMapsCustomMarker@noreply.github.com>
CC: Subscribed <subscribed@noreply.github.com>
Onderwerp: [ivosturm/GoogleMapsCustomMarker] DEPRECATED: store.caller argument of mx.data.action will be removed in version 8.0. The originating page should be passed to mx.data.action as 'origin' instead. (#14)


Warning "DEPRECATED: store.caller argument of mx.data.action will be removed in version 8.0. The originating page should be passed to mx.data.action as 'origin' instead. " when clicking the button which triggers the "on click microflow".

**Comment by ssuijkerbuijk** [comment]
Ok. Thanks.

**Comment by ivosturm** [comment]
Should be fixed with version 3.2.0 of widget
