### ISSUE TITLE
Marker does not show for uncommitted object 

### ISSUE THREAD

**Issue by axelbrink** [ivosturm/GoogleMapsCustomMarker#15]
The widget works great if the location object is committed, but if the object is not committed the marker does not show and the map shows blue sea only. It would be great if the widget would also work for uncommitted objects, because it would be easier to make the page's Cancel button work well if nothing has been commited.

**Comment by ivosturm** [comment]
Hi Axel,

Which version of the widget do you use? And which specific scenario do you mean?

Reason I ask is because the newest version of the widget should work with non-committed changes / non-persistent entities if it is the scenario of a single dataview with a Mendix object as context used in the GoogleMapsCustomMarker widget.

Let me know and I will check next week!



Van: axelbrink <notifications@github.com>
Verzonden: donderdag 1 november 2018 17:17
Aan: ivosturm/GoogleMapsCustomMarker <GoogleMapsCustomMarker@noreply.github.com>
CC: Subscribed <subscribed@noreply.github.com>
Onderwerp: [ivosturm/GoogleMapsCustomMarker] Marker does not show for uncommitted object (#15)


The widget works great if the location object is committed, but if the object is not committed the marker does not show and the map shows blue sea only. It would be great if the widget would also work for uncommitted objects, because it would be easier to make the page's Cancel button work well if nothing has been commited.

**Comment by axelbrink** [comment]
Hi Ivo,
Thanks for your reply! It's version 3.0.1. I just found out that the issue only applies when an XPath constraint is set, which makes sense. Using a data source microflow solves the problem. So there is no issue. Maybe it would be helpful to add a little reminder about database persistence when using the XPath constraint.

**Comment by ivosturm** [comment]
I will add an extra remark in the next release!
