### ISSUE TITLE
Zoom issue using current object as xpath constraint

### ISSUE THREAD

**Issue by PeterDorsman** [ivosturm/GoogleMapsCustomMarker#19]
When I use the XPath constraint "[id='[%CurrentObject%]']", there is only one marker to be shown. In this cases the map is zoomed to somewhere in de middle of the ocean, in stead of the city of Rotterdam, where the marker is positioned. When I zoom out to the world, I can see, the marker is there.

I hope what I have requested is possible. 

![result](https://user-images.githubusercontent.com/40062889/50766898-391d2700-127b-11e9-8408-de7faba6d365.jpg)
![setting1](https://user-images.githubusercontent.com/40062889/50766900-39b5bd80-127b-11e9-8049-2f00f41920a8.JPG)
![setting2](https://user-images.githubusercontent.com/40062889/50766901-39b5bd80-127b-11e9-9a28-e081f9729cd3.JPG)

**Comment by ivosturm** [comment]
Can you shed a bit more light on this scenario you are trying to achieve. Possibly it is not supported. So:

  *   What are the modeler settings?
  *   How is the domain model setup?
  *   Are you trying to show the marker which is the dataview object itself?

Please add some printscreens as well.

Kind regards,
Ivo

Van: PeterDorsman <notifications@github.com>
Verzonden: maandag 7 januari 2019 12:54
Aan: ivosturm/GoogleMapsCustomMarker <GoogleMapsCustomMarker@noreply.github.com>
CC: Subscribed <subscribed@noreply.github.com>
Onderwerp: [ivosturm/GoogleMapsCustomMarker] Zoom issue using current object as xpath constraint (#19)


When I use the XPath constraint "[id='[%CurrentObject%]']", there is only one marker to be shown. In this cases the map is zoomed to somewhere in de middle of the ocean, in stead of the city of Rotterdam, where the marker is positioned. When I zoom out to the world, I can see, the marker is there.

[result]<https://user-images.githubusercontent.com/40062889/50766898-391d2700-127b-11e9-8408-de7faba6d365.jpg>
[setting1]<https://user-images.githubusercontent.com/40062889/50766900-39b5bd80-127b-11e9-8049-2f00f41920a8.JPG>
[setting2]<https://user-images.githubusercontent.com/40062889/50766901-39b5bd80-127b-11e9-9a28-e081f9729cd3.JPG>

Is this something you are able to fix.

**Comment by PeterDorsman** [comment]
Hi Ivo,

Thank you for your response.
I am using mendix 7.20.1 with the google maps module from the store.
I've a module "Projectmodule" with an entity "project".
It has a one to one relation with the entity "location" in the "GoogleMaps"module
On the form Project_NewEdit the location of the project is shown with the GoogleMaps Widget

When an (allowed) user wants to set the location for a new project or wants to change/move an existing location this is done on a popup form. When there isn't a location yet, a microflow creates a new default location entity in the centre of Rotterdam. When there is a location, it is recalled.  With the javacode "CalculateGeo" the location of the marker can be moved to a given adres, for example "Coolsingel 25, Rotterdam". By using the widget GoogleMapsCustomMarker and the option "Toggle Dragging" enabled, the user is able to 'finetune' the position of the marker.

After recalling the location entity in the pop-up form, the GoogleMaps widget, zooms to the the correct location of the marker. The GoogleMapsCustomMarker widget zooms to de the default 0,0 location on the ocean.
![example](https://user-images.githubusercontent.com/40062889/50793316-149b6c00-12c8-11e9-9131-c7a0eb83f300.JPG)

When I zoom out long enough, I can see, the marker is there. So it looks, it is just a "zoom" problem.

In the example the setting of the google maps widget and the GoogleMapsCustomMarker widget are the same.
![instellingen](https://user-images.githubusercontent.com/40062889/50793289-ff264200-12c7-11e9-8f96-8c6b9f8c3bdf.jpg)

Strange thing is, that when I use the java action "CalculateGeo" with the button "Bereken nieuwe locatie", and as a result of that the lat/lon values are changed for the the entity, the GoogleMapsCustomMarker widget zooms to the same (correct!)  area as the GoogleMaps widget, only two markers are shown on the map
![example2](https://user-images.githubusercontent.com/40062889/50793277-f2a1e980-12c7-11e9-9f77-8788f90563fe.JPG)


Hope you can help me

**Comment by ivosturm** [comment]
Hi Peter,

So it seems zooming is not retriggered after the location is set by the data source MF in my widget. Fix should be fairly easy, but then I should be able to reproduce. Best would be a test project from your side, so if you could do that, that would be great. Else some extra questions to single out the exact scenario we are dealing with:
- You have one setting different, ‘Refresh on entity changes’. What happens if also for the CustomMarker widget you set it to ‘Yes’?
- Is it the newest version of my widget?
- Is the entity persistent?
- Is it stored in the database in this data source MF via a commit + potential refresh in client?
- Could you share a snapshot of what the page looks like in the Modeler with the widget in it? Also one from the data source MF?

Kind regards,
Ivo

Op 7 jan. 2019 om 22:04 heeft PeterDorsman <notifications@github.com<mailto:notifications@github.com>> het volgende geschreven:


Hi Ivo,

Thank you for your response.
I am using mendix 7.20.1 with the google maps module from the store.
I've a module "Projectmodule" with an entity "project".
It has a one to one relation with the entity "location" in the "GoogleMaps"module
On the form Project_NewEdit the location of the project is shown with the GoogleMaps Widget

When an (allowed) user wants to set the location for a new project or wants to change/move an existing location this is done on a popup form. When there isn't a location yet, a microflow creates a new default location entity in the centre of Rotterdam. When there is a location, it is recalled. With the javacode "CalculateGeo" the location of the marker can be moved to a given adres, for example "Coolsingel 25, Rotterdam". By using the widget GoogleMapsCustomMarker and the option "Toggle Dragging" enabled, the user is able to 'finetune' the position of the marker.

After recalling the location entity in the pop-up form, the GoogleMaps widget, zooms to the the correct location of the marker. The GoogleMapsCustomMarker widget zooms to de the default 0,0 location on the ocean.
[example]<https://user-images.githubusercontent.com/40062889/50793316-149b6c00-12c8-11e9-9131-c7a0eb83f300.JPG>

When I zoom out long enough, I can see, the marker is there. So it looks, it is just a "zoom" problem.

In the example the setting of the google maps widget and the GoogleMapsCustomMarker widget are the same.
[instellingen]<https://user-images.githubusercontent.com/40062889/50793289-ff264200-12c7-11e9-8f96-8c6b9f8c3bdf.jpg>

Strange thing is, that when I use the java action "CalculateGeo" with the button "Bereken nieuwe locatie", and as a result of that the lat/lon values are changed for the the entity, the GoogleMapsCustomMarker widget zooms to the same (correct!) area as the GoogleMaps widget, only two markers are shown on the map
[example2]<https://user-images.githubusercontent.com/40062889/50793277-f2a1e980-12c7-11e9-9f77-8788f90563fe.JPG>

Hope you can help me

**Comment by ivosturm** [comment]
Hi Peter,

I see you closed the issue. Is it not there anymore? Just curious as I am resolving some other logged bugs and enhancements at the moment.

Kind regards,
Ivo

Van: Ivo Sturm
Verzonden: maandag 7 januari 2019 22:59
Aan: ivosturm/GoogleMapsCustomMarker <reply@reply.github.com>
Onderwerp: Re: [ivosturm/GoogleMapsCustomMarker] Zoom issue using current object as xpath constraint (#19)

Hi Peter,

So it seems zooming is not retriggered after the location is set by the data source MF in my widget. Fix should be fairly easy, but then I should be able to reproduce. Best would be a test project from your side, so if you could do that, that would be great. Else some extra questions to single out the exact scenario we are dealing with:
- You have one setting different, ‘Refresh on entity changes’. What happens if also for the CustomMarker widget you set it to ‘Yes’?
- Is it the newest version of my widget?
- Is the entity persistent?
- Is it stored in the database in this data source MF via a commit + potential refresh in client?
- Could you share a snapshot of what the page looks like in the Modeler with the widget in it? Also one from the data source MF?

Kind regards,
Ivo

Op 7 jan. 2019 om 22:04 heeft PeterDorsman <notifications@github.com<mailto:notifications@github.com>> het volgende geschreven:

Hi Ivo,

Thank you for your response.
I am using mendix 7.20.1 with the google maps module from the store.
I've a module "Projectmodule" with an entity "project".
It has a one to one relation with the entity "location" in the "GoogleMaps"module
On the form Project_NewEdit the location of the project is shown with the GoogleMaps Widget

When an (allowed) user wants to set the location for a new project or wants to change/move an existing location this is done on a popup form. When there isn't a location yet, a microflow creates a new default location entity in the centre of Rotterdam. When there is a location, it is recalled. With the javacode "CalculateGeo" the location of the marker can be moved to a given adres, for example "Coolsingel 25, Rotterdam". By using the widget GoogleMapsCustomMarker and the option "Toggle Dragging" enabled, the user is able to 'finetune' the position of the marker.

After recalling the location entity in the pop-up form, the GoogleMaps widget, zooms to the the correct location of the marker. The GoogleMapsCustomMarker widget zooms to de the default 0,0 location on the ocean.
[example]<https://user-images.githubusercontent.com/40062889/50793316-149b6c00-12c8-11e9-9131-c7a0eb83f300.JPG>

When I zoom out long enough, I can see, the marker is there. So it looks, it is just a "zoom" problem.

In the example the setting of the google maps widget and the GoogleMapsCustomMarker widget are the same.
[instellingen]<https://user-images.githubusercontent.com/40062889/50793289-ff264200-12c7-11e9-8f96-8c6b9f8c3bdf.jpg>

Strange thing is, that when I use the java action "CalculateGeo" with the button "Bereken nieuwe locatie", and as a result of that the lat/lon values are changed for the the entity, the GoogleMapsCustomMarker widget zooms to the same (correct!) area as the GoogleMaps widget, only two markers are shown on the map
[example2]<https://user-images.githubusercontent.com/40062889/50793277-f2a1e980-12c7-11e9-9f77-8788f90563fe.JPG>

Hope you can help me
