### ISSUE TITLE
Latest version breaks widget

### ISSUE THREAD

**Issue by Mcpoowl** [ivosturm/GoogleMapsCustomMarker#5]
Hi Ivo,

I just upgraded to the latest version of the widget, from Mendix 6. However, when using version 1.2.1, the widget breaks, rendering fine, but showing only one object, which is the context object, instead of the object selected in the widget. 

downloading the previous version (1.2.0) and everything works accordingly.

Loging in breaking version (v1.2.1)
![image](https://user-images.githubusercontent.com/2244753/28865351-de493f46-776f-11e7-930a-c06ed7f0430a.png)

Logging in working versoin (v1.2.0)
![image](https://user-images.githubusercontent.com/2244753/28865411-2145c7e2-7770-11e7-98ed-9389858384cb.png)

Obviously, no settings were changed while checking different versions.

**Comment by ivosturm** [comment]
Hi Paul,

What is the scenario in which the widget breaks in the new version? Are you using the widget in a dataview and referring to it in the XPath constraint of the widget?

In the newer version (1.2.1) I fixed a bug related to the contextobject always being retrieved from the database, which is not always necessary. I think this ‘fix’ is now causing your scenario to break.

Can you send me a printscreen of the page + widget settings? That will help greatly in fixing this!

Regards,
Ivo

Van: Paul Ketelaars [mailto:notifications@github.com]
Verzonden: woensdag 2 augustus 2017 10:49
Aan: ivosturm/GoogleMapsCustomMarker <GoogleMapsCustomMarker@noreply.github.com>
CC: Subscribed <subscribed@noreply.github.com>
Onderwerp: [ivosturm/GoogleMapsCustomMarker] Latest version breaks widget (#5)


Hi Ivo,

I just upgraded to the latest version of the widget, from Mendix 6. However, when using version 1.2.1, the widget breaks, rendering fine, but showing only one object, which is the context object, instead of the object selected in the widget.

downloading the previous version (1.2.0) and everything works accordingly.

Loging in breaking version (v1.2.1)
[image]<https://user-images.githubusercontent.com/2244753/28865351-de493f46-776f-11e7-930a-c06ed7f0430a.png>

Logging in working versoin (v1.2.0)
[image]<https://user-images.githubusercontent.com/2244753/28865411-2145c7e2-7770-11e7-98ed-9389858384cb.png>

Obviously, no settings were changed while checking different versions.

**Comment by Mcpoowl** [comment]
Hi Ivo,

Thanks for the quick response. Indeed it's in a dataview, with an XPath Constraint on it.

See screenshot:

![image](https://user-images.githubusercontent.com/2244753/28865958-d29e4e1e-7771-11e7-9098-5d1f65a27054.png)


//edit: I accidentally created the screenshot in my Mendix 6 branch and thus the older widget version, but the XPath setup remains the same even in the new version :)

**Comment by ivosturm** [comment]
Hi Paul, I just added an upgraded version of the widget with a fix for this bug in the AppStore. Can you verify it is working again for your scenario?

**Comment by Mcpoowl** [comment]
Works like a charm @ivosturm . Thanks for the quick fix!
